version: '3.4'

x-base: &base
  image: minidocks/base
  volumes:
    - .:$PWD
    - ~/.composer/cache:/composer-cache
    - ~/.composer/auth.json:/composer/auth.json
  working_dir: $PWD
  command: sshd

services:
  php:
    <<: *base
    image: "minidocks/php-tools:${PHP_VERSION:-8.0}"
    depends_on:
      - git
    environment:
      ALIAS_GIT: ssh -y git git

  git:
    <<: *base
    image: minidocks/git
