name: Tests

on:
  push: ~
  pull_request: ~

jobs:
  phpunit:
    name: PHPUnit on ${{ matrix.php }} (${{ matrix.deps_strategy }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deps_strategy: [ latest, lowest ]
        php: [ 7.2, 7.3, 7.4, '8.0' ]
    steps:
      - name: Update code
        uses: actions/checkout@v2
      - name: Install dependencies
        env:
          PHP_VERSION: ${{ matrix.php }}
          DEPS_STRATEGY: ${{ matrix.deps_strategy }}
        run: ./run deps:$DEPS_STRATEGY
      - name: Tests
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: ./run tests
